# Generated by Django 5.0.1 on 2024-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consumidor_emisor_empresa_especie_importarasistencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuarioapp',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Proceso', 'Proceso'), ('Supervisor', 'Supervisor')], default='Administrador', max_length=25),
        ),
    ]
