# Generated by Django 5.0.1 on 2024-03-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_tipo_usuarioapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importarasistenciadetalle',
            name='cantidad',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
