# Generated by Django 4.0 on 2024-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importarasistencia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
