# Generated by Django 4.0 on 2024-03-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_importarasistencia_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('idcodigogeneral', models.CharField(max_length=10)),
                ('idactividad', models.CharField(max_length=10)),
                ('idlabor', models.CharField(max_length=10)),
                ('idconsumidor', models.CharField(max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Encabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.CharField(max_length=10)),
                ('tipo_envio', models.CharField(max_length=1)),
                ('idresponsable', models.CharField(max_length=10)),
                ('idplanilla', models.CharField(max_length=10)),
                ('idemisor', models.CharField(max_length=10)),
                ('idturno', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=8)),
                ('idsucursal', models.CharField(max_length=10)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encabezado_rel', to='api.detalle')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='encabezado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_rel', to='api.encabezado'),
        ),
    ]
