# Generated by Django 4.0 on 2024-03-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_detalle_encabezado_detalle_encabezado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encabezado',
            name='detalle',
        ),
        migrations.AlterField(
            model_name='detalle',
            name='encabezado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.encabezado'),
        ),
    ]
