# Generated by Django 4.0 on 2024-03-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_encabezado_detalle_alter_detalle_encabezado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle',
        ),
        migrations.DeleteModel(
            name='Encabezado',
        ),
    ]
