# Generated by Django 4.0 on 2024-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_detalle_delete_encabezado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
