# Generated by Django 4.0 on 2024-03-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_imagen_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosNisira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEnviado', models.DateField(auto_now_add=True)),
                ('FechaNisira', models.DateField()),
                ('Encabezado', models.CharField(max_length=100)),
                ('KilosEnviados', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios'),
        ),
    ]
