# Generated by Django 4.0 on 2024-03-30 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_enviosnisira_alter_customuser_imagen_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviosnisira',
            name='HoraEnvio',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
