# Generated by Django 4.0 on 2024-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enviosnisira_horaenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviosnisira',
            name='IdEnvio',
            field=models.CharField(default='DEFAULT_VALUE_HERE', max_length=50, unique=True),
        ),
    ]
