# Generated by Django 4.0 on 2024-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_enviosnisira_idenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviosnisira',
            name='IdEnvio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
