# Generated by Django 4.0 on 2024-03-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_enviosnisira_idenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviosnisira',
            name='IdEnvio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
