# Generated by Django 4.0 on 2024-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_enviosnisira_idenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviosnisira',
            name='KilosEnviados',
            field=models.CharField(max_length=50),
        ),
    ]
