# Generated by Django 4.0 on 2024-05-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customuser_descripcion_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importarasistencia',
            name='hora',
        ),
    ]
