# Generated by Django 4.0 on 2024-05-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_importarasistencia_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='importarasistencia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
