# Generated by Django 4.0 on 2024-05-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_importarasistencia_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='importarasistencia',
            name='tipo_empleado',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
