# Generated by Django 4.0 on 2024-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_importarasistencia_tipo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='importarasistenciadetalle',
            name='tipo_empleado',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
