# Generated by Django 4.0 on 2024-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_importarasistenciadetalle_tipo_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Externos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('nombre_apellido', models.CharField(max_length=255)),
            ],
        ),
    ]
