# Generated by Django 4.0 on 2024-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_externos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externos',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
